//
//  ParentPresenter.swift
//  DataPassing
//
//  Created by Raymond Law on 3/22/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParentPresentationLogic
{
  func presentGreeting(response: Parent.ShowGreeting.Response)
  func presentTellChild(response: Parent.TellChild.Response)
}

class ParentPresenter: ParentPresentationLogic
{
  weak var viewController: ParentDisplayLogic?
  
  // MARK: Show greeting
  
  func presentGreeting(response: Parent.ShowGreeting.Response)
  {
    let greeting = response.name.isEmpty ? "Hello" : "\(response.name), nah, let's just shop on Amazon on my iPad."
    let viewModel = Parent.ShowGreeting.ViewModel(greeting: greeting)
    viewController?.displayGreeting(viewModel: viewModel)
  }
  
  // MARK: Tell child
  
  func presentTellChild(response: Parent.TellChild.Response)
  {
    let viewModel = Parent.TellChild.ViewModel()
    viewController?.displayTellChild(viewModel: viewModel)
  }
}
