//
//  ParentModels.swift
//  DataPassing
//
//  Created by Raymond Law on 3/22/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Parent
{
  // MARK: Use cases
  
  enum ShowGreeting
  {
    struct Request
    {
    }
    struct Response
    {
      var name: String
    }
    struct ViewModel
    {
      var greeting: String
    }
  }
  
  enum TellChild
  {
    struct Request
    {
      var name: String
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
