//
//  ParentRouter.swift
//  DataPassing
//
//  Created by Raymond Law on 3/22/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ParentRoutingLogic
{
  func routeToChild(segue: UIStoryboardSegue?)
}

protocol ParentDataPassing
{
  var dataStore: ParentDataStore? { get }
}

class ParentRouter: NSObject, ParentRoutingLogic, ParentDataPassing
{
  weak var viewController: ParentViewController?
  var dataStore: ParentDataStore?
  
  // MARK: Routing
  
  func routeToChild(segue: UIStoryboardSegue?)
  {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "ChildViewController") as! ChildViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToChild(source: dataStore!, destination: &destinationDS)
    navigateToChild(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToChild(source: ParentViewController, destination: ChildViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToChild(source: ParentDataStore, destination: inout ChildDataStore)
  {
    destination.name = source.name
  }
}
