//
//  ChildViewController.swift
//  DataPassing
//
//  Created by Raymond Law on 3/22/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildDisplayLogic: class
{
  func displayGreeting(viewModel: Child.ShowGreeting.ViewModel)
  func displayTellParent(viewModel: Child.TellParent.ViewModel)
}

class ChildViewController: UIViewController, ChildDisplayLogic
{
  var interactor: ChildBusinessLogic?
  var router: (NSObjectProtocol & ChildRoutingLogic & ChildDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ChildInteractor()
    let presenter = ChildPresenter()
    let router = ChildRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
  }
  
  override func viewWillAppear(_ animated: Bool)
  {
    super.viewWillAppear(animated)
    showGreeting()
  }
  
  // MARK: Show greeting
  
  @IBOutlet weak var label: UILabel!
  @IBOutlet weak var textField: UITextField!
  
  func showGreeting()
  {
    let request = Child.ShowGreeting.Request()
    interactor?.showGreeting(request: request)
  }
  
  func displayGreeting(viewModel: Child.ShowGreeting.ViewModel)
  {
    label.text = viewModel.greeting
  }
  
  // MARK: Tell parent
  
  @IBAction func buttonTapped(_ sender: Any)
  {
    tellParent()
  }
  
  func tellParent()
  {
    let name = textField.text!
    let request = Child.TellParent.Request(name: name)
    interactor?.tellParent(request: request)
  }
  
  func displayTellParent(viewModel: Child.TellParent.ViewModel)
  {
    router?.routeToParent(segue: nil)
  }
}
