//
//  ChildRouter.swift
//  DataPassing
//
//  Created by Raymond Law on 3/22/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChildRoutingLogic
{
  func routeToParent(segue: UIStoryboardSegue?)
}

protocol ChildDataPassing
{
  var dataStore: ChildDataStore? { get }
}

class ChildRouter: NSObject, ChildRoutingLogic, ChildDataPassing
{
  weak var viewController: ChildViewController?
  var dataStore: ChildDataStore?
  
  // MARK: Routing
  
  func routeToParent(segue: UIStoryboardSegue?)
  {
    let destinationVC = viewController?.presentingViewController as! ParentViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToParent(source: dataStore!, destination: &destinationDS)
    navigateToParent(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToParent(source: ChildViewController, destination: ParentViewController)
  {
    source.dismiss(animated: true, completion: nil)
  }
  
  // MARK: Passing data
  
  func passDataToParent(source: ChildDataStore, destination: inout ParentDataStore)
  {
    destination.name = source.name
  }
}
