//
//  ChildInteractor.swift
//  DataPassing
//
//  Created by Raymond Law on 3/22/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildBusinessLogic
{
  func showGreeting(request: Child.ShowGreeting.Request)
  func tellParent(request: Child.TellParent.Request)
}

protocol ChildDataStore
{
  var name: String { get set }
}

class ChildInteractor: ChildBusinessLogic, ChildDataStore
{
  var presenter: ChildPresentationLogic?
  var worker: ChildWorker?
  var name: String = ""
  
  // MARK: Show greeting
  
  func showGreeting(request: Child.ShowGreeting.Request)
  {
    let response = Child.ShowGreeting.Response(name: name)
    presenter?.presentGreeting(response: response)
  }
  
  // MARK: Tell child
  
  func tellParent(request: Child.TellParent.Request)
  {
    name = request.name
    let response = Child.TellParent.Response()
    presenter?.presentTellParent(response: response)
  }
}
